POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json

{
	"name": "Ricardo",
	"email": "ricardo@gmail.com"
}

###

PATCH http://localhost:3333/users/bc96fd25-8b0a-4432-b178-01be43b92807/admin HTTP/1.1

###

GET http://localhost:3333/users/ec752414-23d6-4fc4-9e44-e90f699df98e HTTP/1.1

###

GET http://localhost:3333/users HTTP/1.1
user_id: bc96fd25-8b0a-4432-b178-01be43b92807